name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Run Unit Tests
        run: npm run test:unit

      #   - name: Run Static Code Analysis (SonarCloud)
      #     uses: sonarsource/sonarcloud-github-action@v2
      #     with:
      #       projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
      #       organization: ${{ secrets.SONAR_ORGANIZATION }}
      #       token: ${{ secrets.SONAR_TOKEN }}

      - name: Repo Scanning (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          format: "table"

      - name: Build Docker Image
        run: |
          docker build -t xcoder420/bloginary .

      - name: Image Scanning (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "image"
          image-ref: "xcoder420/bloginary"
          format: "table"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag xcoder420/bloginary xcoder420/bloginary:latest
          docker push xcoder420/bloginary:latest
